influxdb:
  database_name: pi_mood
buttons:
  - pin: 21
    label: great
    value: 5
  - pin: 19
    label: happy
    value: 4
  - pin: 15
    label: meh
    value: 3
  - pin: 13
    label: unhappy
    value: 2
  - pin: 11
    label: sad
    value: 1
led:
  pin: 37
